JsonTestMVC/Controllers/TestModalController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using JsonTestMVC.Models;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using JsonTestMVC.Utilities;

namespace JsonTestMVC.Controllers
{
    public class TestModalController : Controller
    {
        // GET: TestModal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowBootStrapModal(int testid1, int testid2)
        {
            ViewBag.testid1 = testid1;
            ViewBag.testid2 = testid2;
            return PartialView("_TestPartial");
        }

        //Install-Package itextsharp.xmlworker -Version 5.5.13 
        //http://jsfiddle.net/a49cA/1/

        public ActionResult GeneratePDF()
        {
            bool IsPdfGenerated = false;

            List<Student> studentsVM = new List<Student>
            {
                new Student {ID=1,FirstName="Joy",      LastName="Roy",     FavouriteGames="Hocky"},
                new Student {ID=2,FirstName="Raja",     LastName="Basu",    FavouriteGames="Cricket"},
                new Student {ID=3,FirstName="Arijit",   LastName="Banerjee",FavouriteGames="Foot Ball"},
                new Student {ID=4,FirstName="Dibyendu", LastName="Saha",    FavouriteGames="Tennis"},
                new Student {ID=5,FirstName="Sanjeeb",  LastName="Das",     FavouriteGames="Hocky"},
            };

            var viewToString = StringUtilities.RenderViewToString(ControllerContext, "~/Views/Shared/_Report.cshtml", studentsVM, true);
            string filepath = HttpContext.Server.MapPath("~/PDFArchives/") + "mypdf.pdf";

            try
            {
                StringReader sr = new StringReader(viewToString);
                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 30f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, new FileStream(filepath, FileMode.Create));
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                IsPdfGenerated = true;
            }
            catch (Exception ex)
            {
                IsPdfGenerated = false;
            }

            //return Json(new { fileName = filepath, errorMessage = (IsPdfGenerated ? "" : "Error occured when pdf generated") });
            return Json(new { Msg = (IsPdfGenerated ? "PDF generated properly" : "Error occured when pdf generated") });
        }

        [Route("DownloadPDF")]
        [HttpGet]
        public void DownloadPDF()
        {
            //bool IsPdfGenerated = false;
            ViewBag.SerialNo = "AC001";
            ViewBag.hobby = "Football";
            ViewBag.sex = "M";

            List<Student> studentsVM = new List<Student>
            {
                new Student {ID=1,FirstName="Joy",      LastName="Roy",     FavouriteGames="Hocky"},
                new Student {ID=2,FirstName="Raja",     LastName="Basu",    FavouriteGames="Cricket"},
                new Student {ID=3,FirstName="Arijit",   LastName="Banerjee",FavouriteGames="Foot Ball"},
                new Student {ID=4,FirstName="Dibyendu", LastName="Saha",    FavouriteGames="Tennis"},
                new Student {ID=5,FirstName="Sanjeeb",  LastName="Das",     FavouriteGames="Hocky"},
            };

            var viewToString = StringUtilities.RenderViewToString(ControllerContext, "~/Views/Shared/_Report.cshtml", studentsVM, true);
            string filepath = HttpContext.Server.MapPath("~/PDFArchives/") + "mypdf.pdf";

            MemoryStream workStream = new MemoryStream();
            StringReader sr = new StringReader(viewToString);
            Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 30f, 0f);
            PdfWriter writer = PdfWriter.GetInstance(pdfDoc, System.Web.HttpContext.Current.Response.OutputStream);
            writer.CloseStream = false;
            pdfDoc.Open();
            XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
            pdfDoc.Close();

            System.Web.HttpContext.Current.Response.ContentType = "pdf/application";
            System.Web.HttpContext.Current.Response.AddHeader("content-disposition", "attachment;" +
                    "filename=sample.pdf");
            System.Web.HttpContext.Current.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            System.Web.HttpContext.Current.Response.Write(pdfDoc);
            System.Web.HttpContext.Current.Response.End();
        }

        //public FileStreamResult GetPdf()
        //{
        //    var memoryStream = new MemoryStream();
        //    Document document = new Document();
        //    PdfWriter.GetInstance(document, memoryStream);
        //    document.Open();
        //    document.Add(new Chunk("Hello World"));

        //    writer.CloseStream = false;
        //    document.Close();
        //    memoryStream.Position = 0;

        //    System.Net.Mime.ContentDisposition contentDisposition = new System.Net.Mime.ContentDisposition
        //    {
        //        FileName = fileName,
        //        Inline = true
        //    };
        //    Response.Headers.Add("Content-Disposition", contentDisposition.ToString());
        //    return File(pdfFile, "application/pdf");

        //    return FileStreamResult(memoryStream, "application/pdf", "Myfile.pdf");

        // https://simpledotnetsolutions.wordpress.com/2012/11/01/itextsharp-creating-form-fields/
        //}


    }
}

JsonTestMVC/Views/TestModal/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br /><br /><br />
<div class="row">
    @Html.ActionLink("Show Dialog", "ShowBootStrapModal", new { testid1 = 1, testid2 = 101 }, new { id = "lnkPrintBol" })

    <button type="button" id="btndownload">Download as PDF</button>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary bol_print_modal_save">Save changes</button>

                <button type="button" class="btn btn-primary bol_save_as_pdf">Save as PDF</button>

                <button type="button" class="btn btn-primary bol_download_as_pdf">Download as PDF</button>
                <button type="button" class="btn btn-primary bol_Print_as_pdf">Print as PDF</button>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script>
    $(document).ready(function () {

        $("#lnkPrintBol").click(function () {
            var linkurl = $(this).attr("href");
            alert(linkurl);
            //$('.modal-body').html('<b>Hello testing data</b>');
            //$('#myModal').modal('show');


            $(".modal-body").load(linkurl, function (responseTxt, statusTxt, xhr) {
                if (statusTxt == "success") {
                    alert("External content loaded successfully!");
                    //$('#myModal').modal({ backdrop: 'static', keyboard: false }, 'show');
                    $('#myModal').modal('show');
                }
                if (statusTxt == "error") {
                    alert("Error: " + xhr.status + ": " + xhr.statusText);
                }
            });
            return false;
        });

        $(".bol_print_modal_save").click(function () {
            alert('Save clicked');
            $('#myModal').modal('hide');
            return false;
        });

        $('#myModal').on('hidden.bs.modal', function () {
            //write code here when user click on close button
            alert('removing modal')
            $(this).removeData('bs.modal');
            $('#modal-container .modal-content').empty();
        });

        $(".bol_save_as_pdf").click(function () {
            alert('Save as pdf clicked');
            $.ajax({
                type: "GET",
                url: '@Url.Action("GeneratePDF", "TestModal")',
                success: function (data) {
                    @*alert('PDF generate successfully');
                        window.location = '@Url.Action("DownloadAttachment", "PostDetail", new { studentId = 123 })';*@
                    alert(data.Msg);
                },
                error: function (xhr, status, error) {
                    //$("#dataDiv").html("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                }
            });
            return false;
        });

        $(".bol_download_as_pdf").click(function () {
            alert('Save as pdf clicked');
            $.ajax({
                type: "POST",
                url: '@Url.Action("DownloadPDF", "TestModal")',
                success: function (data) {
                    @*alert('PDF generate successfully');
                        window.location = '@Url.Action("DownloadAttachment", "PostDetail", new { studentId = 123 })';*@
                    //alert(data.Msg);
                },
                error: function (xhr, status, error) {
                    //$("#dataDiv").html("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                }
            });
            return false;
        });

        $("#btndownload").click(function () {
            window.location = '@Url.Action("DownloadPDF", "TestModal")';
            return false;
        });
    });
    </script>
}